name: Build Linux

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Build
      run: ./tools/build_linux.sh

    - name: Upload Release Assets
      uses: wzshiming/action-upload-release-assets@v1
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
