name: Build Linux gtk3

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24

    - name: Build dependents
      run: |
        sudo apt-get update -y
        sudo apt-get install libgtk-3-dev libappindicator3-dev -y

    - name: Build
      run: ./tools/build_linux_gtk3.sh

    - name: Upload Release Assets
      uses: wzshiming/action-upload-release-assets@v1
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
